#!/bin/sh

# Copyright (c) 2006 Sokolov Alexey <nullbsd@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

if [ `whoami` != "root" ]; then
    echo "I need root permission!"
    exit
fi

pppfile="/etc/ppp/ppp.conf"

if [ ! -f $pppfile ]; then
    (cp -f /usr/share/examples/ppp/ppp.conf.sample $pppfile) > /dev/null
fi

clear

echo "Name of dialup connection: "
read  connectname

echo "Modem port (example: cuad1): "
read port

echo "Phone number (example: p1234567)"
read phone

echo "User name (example: Us3r):"
read username

echo "Password (example: mypas5wD)"
read passwd

clear

echo "You data: "
echo "---"
echo "Name connection: $connectname"
echo "Modem port: $port"
echo "Phone number: $phone"
echo "User name: $username"
echo "Password: $passwd"
echo "---"
echo
echo "Write this options in file $pppfile (y/n)? "
read key

if [ $key != "y" ]; then
    echo "Exiting..."
    exit
fi

echo $connectname":" >> $pppfile
echo " set device /dev/$port"  >> $pppfile
echo " set phone $phone" >> $pppfile
echo " set authname \"$username\"" >> $pppfile
echo " set authkey \"$passwd\"" >> $pppfile

echo
echo "Please, use program \"/sysutils/spp\" (or \"/usr/sbin/ppp\") for dialup connection."
