# #####################################################################
# Automatically generated by qmake (2.01a) Tue Jun 17 18:45:29 2008
# #####################################################################
TEMPLATE = app
TARGET = 
QT += core \
    gui \
    network \
    xml
CONFIG += debug_and_release
DESTDIR = build/bin
OBJECTS_DIR = build/obj
UI_DIR = build/uic
MOC_DIR = build/moc
RCC_DIR = build/rcc
DEPENDPATH += . \
    src \
    translation \
    src/plugins \
    protocol/oscar/icq \
    protocol/oscar/icq/settings \
    src/idle
INCLUDEPATH += . \
    src \
    src/plugins \
    protocol/oscar/icq \
    protocol/oscar/icq/settings \
    src/idle

# Input
HEADERS += protocol/oscar/icq/buddycaps.h \
    src/aboutinfo.h \
    src/accountbutton.h \
    src/contactseparator.h \
    src/logindialog.h \
    src/mainsettings.h \
    src/pluginsettings.h \
    src/qutim.h \
    src/qutimsettings.h \
    src/plugins/plugininterfaces.h \
    protocol/oscar/icq/acceptauthdialog.h \
    protocol/oscar/icq/addbuddydialog.h \
    protocol/oscar/icq/addrenamedialog.h \
    protocol/oscar/icq/buddypicture.h \
    protocol/oscar/icq/buffer.h \
    protocol/oscar/icq/chatwindow.h \
    protocol/oscar/icq/clientIdentification.h \
    protocol/oscar/icq/clientidentify.h \
    protocol/oscar/icq/clientmd5login.h \
    protocol/oscar/icq/closeconnection.h \
    protocol/oscar/icq/connection.h \
    protocol/oscar/icq/contactlist.h \
    protocol/oscar/icq/customstatusdialog.h \
    protocol/oscar/icq/deletecontactdialog.h \
    protocol/oscar/icq/emoticonmenu.h \
    protocol/oscar/icq/filerequestwindow.h \
    protocol/oscar/icq/filetransfer.h \
    protocol/oscar/icq/filetransferwindow.h \
    protocol/oscar/icq/flap.h \
    protocol/oscar/icq/historyview.h \
    protocol/oscar/icq/historyxml.h \
    protocol/oscar/icq/icqaccount.h \
    protocol/oscar/icq/icqmessage.h \
    protocol/oscar/icq/icqtabwidget.h \
    protocol/oscar/icq/icqtextbrowser.h \
    protocol/oscar/icq/icqtextedit.h \
    protocol/oscar/icq/metainformation.h \
    protocol/oscar/icq/modifyitem.h \
    protocol/oscar/icq/movielabel.h \
    protocol/oscar/icq/multiplesending.h \
    protocol/oscar/icq/oscarprotocol.h \
    protocol/oscar/icq/passwordchangedialog.h \
    protocol/oscar/icq/passworddialog.h \
    protocol/oscar/icq/pluginsystem.h \
    protocol/oscar/icq/privacylistwindow.h \
    protocol/oscar/icq/readawaydialog.h \
    protocol/oscar/icq/requestauthdialog.h \
    protocol/oscar/icq/searchuser.h \
    protocol/oscar/icq/serverloginreply.h \
    protocol/oscar/icq/servicessetup.h \
    protocol/oscar/icq/snac.h \
    protocol/oscar/icq/snacchannel.h \
    protocol/oscar/icq/statusdialog.h \
    protocol/oscar/icq/statusiconfactory.h \
    protocol/oscar/icq/statusiconsclass.h \
    protocol/oscar/icq/tabchatwindow.h \
    protocol/oscar/icq/tlv.h \
    protocol/oscar/icq/traymessage.h \
    protocol/oscar/icq/traymessagetextfield.h \
    protocol/oscar/icq/treebuddyitem.h \
    protocol/oscar/icq/treegroupitem.h \
    protocol/oscar/icq/userinformation.h \
    protocol/oscar/icq/notewidget.h \
    protocol/oscar/icq/soundevents.h \
    protocol/oscar/icq/settings/antispamsettings.h \
    protocol/oscar/icq/settings/contactlistsettings.h \
    protocol/oscar/icq/settings/emoticonsettings.h \
    protocol/oscar/icq/settings/eventssettings.h \
    protocol/oscar/icq/settings/historysettings.h \
    protocol/oscar/icq/settings/icqsettings.h \
    protocol/oscar/icq/settings/messagingsettings.h \
    protocol/oscar/icq/settings/networksettings.h \
    protocol/oscar/icq/settings/statussettings.h \
    protocol/oscar/icq/settings/soundsettings.h \
    src/idle/idle.h
FORMS += src/aboutinfo.ui \
    src/logindialog.ui \
    src/mainsettings.ui \
    src/pluginsettings.ui \
    src/qutim.ui \
    src/qutimsettings.ui \
    protocol/oscar/icq/acceptauthdialog.ui \
    protocol/oscar/icq/addbuddydialog.ui \
    protocol/oscar/icq/addrenamedialog.ui \
    protocol/oscar/icq/chatwindow.ui \
    protocol/oscar/icq/customstatusdialog.ui \
    protocol/oscar/icq/deletecontactdialog.ui \
    protocol/oscar/icq/emoticonmenu.ui \
    protocol/oscar/icq/filerequestwindow.ui \
    protocol/oscar/icq/filetransferwindow.ui \
    protocol/oscar/icq/historyview.ui \
    protocol/oscar/icq/multiplesending.ui \
    protocol/oscar/icq/passwordchangedialog.ui \
    protocol/oscar/icq/passworddialog.ui \
    protocol/oscar/icq/privacylistwindow.ui \
    protocol/oscar/icq/readawaydialog.ui \
    protocol/oscar/icq/requestauthdialog.ui \
    protocol/oscar/icq/searchuser.ui \
    protocol/oscar/icq/statusdialog.ui \
    protocol/oscar/icq/tabchatwindow.ui \
    protocol/oscar/icq/traymessage.ui \
    protocol/oscar/icq/userinformation.ui \
    protocol/oscar/icq/notewidget.ui \
    protocol/oscar/icq/settings/antispamsettings.ui \
    protocol/oscar/icq/settings/contactlistsettings.ui \
    protocol/oscar/icq/settings/emoticonsettings.ui \
    protocol/oscar/icq/settings/eventssettings.ui \
    protocol/oscar/icq/settings/historysettings.ui \
    protocol/oscar/icq/settings/icqsettings.ui \
    protocol/oscar/icq/settings/messagingsettings.ui \
    protocol/oscar/icq/settings/networksettings.ui \
    protocol/oscar/icq/settings/statussettings.ui \
    protocol/oscar/icq/settings/soundsettings.ui
SOURCES += main.cpp \
    src/aboutinfo.cpp \
    src/accountbutton.cpp \
    src/contactseparator.cpp \
    src/logindialog.cpp \
    src/mainsettings.cpp \
    src/pluginsettings.cpp \
    src/qutim.cpp \
    src/qutimsettings.cpp \
    protocol/oscar/icq/acceptauthdialog.cpp \
    protocol/oscar/icq/addbuddydialog.cpp \
    protocol/oscar/icq/addrenamedialog.cpp \
    protocol/oscar/icq/buddypicture.cpp \
    protocol/oscar/icq/buffer.cpp \
    protocol/oscar/icq/chatwindow.cpp \
    protocol/oscar/icq/clientIdentification.cpp \
    protocol/oscar/icq/clientidentify.cpp \
    protocol/oscar/icq/clientmd5login.cpp \
    protocol/oscar/icq/closeconnection.cpp \
    protocol/oscar/icq/connection.cpp \
    protocol/oscar/icq/contactlist.cpp \
    protocol/oscar/icq/customstatusdialog.cpp \
    protocol/oscar/icq/deletecontactdialog.cpp \
    protocol/oscar/icq/emoticonmenu.cpp \
    protocol/oscar/icq/filerequestwindow.cpp \
    protocol/oscar/icq/filetransfer.cpp \
    protocol/oscar/icq/filetransferwindow.cpp \
    protocol/oscar/icq/flap.cpp \
    protocol/oscar/icq/historyview.cpp \
    protocol/oscar/icq/historyxml.cpp \
    protocol/oscar/icq/icqaccount.cpp \
    protocol/oscar/icq/icqmessage.cpp \
    protocol/oscar/icq/icqtabwidget.cpp \
    protocol/oscar/icq/icqtextbrowser.cpp \
    protocol/oscar/icq/icqtextedit.cpp \
    protocol/oscar/icq/metainformation.cpp \
    protocol/oscar/icq/movielabel.cpp \
    protocol/oscar/icq/multiplesending.cpp \
    protocol/oscar/icq/oscarprotocol.cpp \
    protocol/oscar/icq/passwordchangedialog.cpp \
    protocol/oscar/icq/passworddialog.cpp \
    protocol/oscar/icq/pluginsystem.cpp \
    protocol/oscar/icq/privacylistwindow.cpp \
    protocol/oscar/icq/readawaydialog.cpp \
    protocol/oscar/icq/requestauthdialog.cpp \
    protocol/oscar/icq/searchuser.cpp \
    protocol/oscar/icq/serverloginreply.cpp \
    protocol/oscar/icq/servicessetup.cpp \
    protocol/oscar/icq/snac.cpp \
    protocol/oscar/icq/snacchannel.cpp \
    protocol/oscar/icq/statusdialog.cpp \
    protocol/oscar/icq/statusiconfactory.cpp \
    protocol/oscar/icq/statusiconsclass.cpp \
    protocol/oscar/icq/tabchatwindow.cpp \
    protocol/oscar/icq/tlv.cpp \
    protocol/oscar/icq/traymessage.cpp \
    protocol/oscar/icq/traymessagetextfield.cpp \
    protocol/oscar/icq/treebuddyitem.cpp \
    protocol/oscar/icq/treegroupitem.cpp \
    protocol/oscar/icq/userinformation.cpp \
    protocol/oscar/icq/notewidget.cpp \
    protocol/oscar/icq/soundevents.cpp \
    protocol/oscar/icq/settings/antispamsettings.cpp \
    protocol/oscar/icq/settings/contactlistsettings.cpp \
    protocol/oscar/icq/settings/emoticonsettings.cpp \
    protocol/oscar/icq/settings/eventssettings.cpp \
    protocol/oscar/icq/settings/historysettings.cpp \
    protocol/oscar/icq/settings/icqsettings.cpp \
    protocol/oscar/icq/settings/messagingsettings.cpp \
    protocol/oscar/icq/settings/networksettings.cpp \
    protocol/oscar/icq/settings/statussettings.cpp \
    protocol/oscar/icq/settings/soundsettings.cpp \
    src/idle/idle.cpp
RESOURCES += qutim.qrc
TRANSLATIONS += translation/qutim_dump.ts \
    translation/qutim_lt.ts \
    translation/qutim_ru.ts
win32 { 
    HEADERS += src/ex/exsystrayicon.h
    SOURCES += src/ex/exsystrayicon.cpp \
        src/idle/idle_win.cpp
}
macx { 
    HEADERS += src/ex/exsystrayicon.h
    SOURCES += src/ex/exsystrayicon.cpp \
        src/idle/idle_mac.cpp
    ICON = icons/qutim.icns
    CONFIG += x86 \
        ppc
}
unix:!mac:SOURCES += src/idle/idle_x11.cpp
